### ISSUE TITLE
Which CL packages are used?

### ISSUE THREAD

**Issue by anonimitoraf** [kssytsrk/.nyxt.d#2]
Hi!

Very new to Common Lisp. I tried to run your `theme.lisp` but I got this:
```
Symbol "MARKUP" not found in the MARKUP package.

  Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(defvar ...">
   [Condition of type SB-INT:SIMPLE-READER-PACKAGE-ERROR]

Restarts:
 0: [CONTINUE] Use symbol anyway.
 1: [RETRY] Retry SLIME interactive evaluation request.
 2: [*ABORT] Return to SLIME's top level.
 3: [ABORT] abort thread (#<THREAD "worker" RUNNING {10080AA623}>)
```

This is despite installing (I think) the `markup` package via Quicklisp:
```
NYXT-USER> (ql:quickload :markup)
To load "markup":
Load 5 ASDF systems:
alexandria asdf named-readtables str
trivial-gray-streams
Install 1 Quicklisp release:
markup
                                        ; Fetching #<URL "http://beta.quicklisp.org/archive/markup/2021-08-07/markup-20210807-git.tgz">
                                        ; 16.90KB
==================================================
17,307 bytes in 0.19 seconds (88.95KB/sec)
                                        ; Loading "markup"
......
(:MARKUP)
```

Am I doing something wrong? And as a general question, which other packages have you used? 
I'm coming from Clojure where deps are listed in project.clj. Is there an equivalent in CL?

**Comment by kssytsrk** [comment]
Hello. The package error is probably not due to a missing package, but due to the changes in Nyxt codebase. My guess is that they have removed the `markup` package and rewrote the theming interface I used to hook up my code to (which used the `markup` package, that is apparently not included in Nyxt anymore). 
I'm afraid the only immediate solution right now would be going back to 2-pre-release-7 version of Nyxt, where my config code worked (as far as I remember, feel free to contact me if it doesn't). 
I might fix this for the new versions a bit later, I am not actively using Nyxt right now and hadn't even managed to get Nyxt to run on FreeBSD (which I'm using exclusively right now), so that makes improving my config a bit harder. 
...Or you can try to fix it yourself, the main thing to do is probably finding information on how to configure Nyxt's interface in the new version. You can read Nyxt's code, or maybe ask for some pointers on [Nyxt's forum](https://discourse.atlas.engineer). 

> Am I doing something wrong? 

Loading a package by hand like that is a bit unusual when you are trying to run someone else's code that is complex enough to have dependencies. With "well-written" code, packages are usually fetched on-the-go, using package management systems.

> And as a general question, which other packages have you used?

Have not used any, apart from what was included in Nyxt 2-pre-release-7.

> I'm coming from Clojure where deps are listed in project.clj. Is there an equivalent in CL?

I have never used Clojure, but if I were to introduce additional dependencies into my CL code I would make it into a package, [similarly to how Nyxt handles dependencies](https://github.com/atlas-engineer/nyxt/blob/master/nyxt.asd#L28). If you want to learn more about Common Lisp's package management system, it might be useful to check [this CL cookbook page](https://lispcookbook.github.io/cl-cookbook/packages.html) (and the linked guide), [this stackoverflow question](https://stackoverflow.com/questions/10112797/proper-way-of-defining-packages-using-asdfdefsystem-and-quickproject) (together with the comments and answers to it), [ASDF manual](https://www.common-lisp.net/project/asdf/asdf.html) for specifics, and a search engine for everything else.

**Comment by anonimitoraf** [comment]
I see!
> I'm afraid the only immediate solution right now would be going back to 2-pre-release-7 version of Nyxt, where my config code worked (as far as I remember, feel free to contact me if it doesn't).

It's ok, I'll just adjust the code accordingly (instead of rolling back) :)

> Loading a package by hand like that is a bit unusual when you are trying to run someone else's code that is complex enough to have dependencies. With "well-written" code, packages are usually fetched on-the-go, using package management systems.

Yep, this is what I usually assume too

> I have never used Clojure, but if I were to introduce additional dependencies into my CL code I would make it into a package, similarly to how Nyxt handles dependencies. If you want to learn more about Common Lisp's package management system, it might be useful to check this CL cookbook page (and the linked guide), this stackoverflow question (together with the comments and answers to it), ASDF manual for specifics, and a search engine for everything else.

Thanks for the links :D

**Comment by kssytsrk** [comment]
Ok. Can I close this issue or is there something else to it?

**Comment by anonimitoraf** [comment]
Ah sorry, just forgot to do so
